sudo: required 

services:
 - docker


before_install:
 - docker build -t nishadguru/docker-react -f Dockerfile.dev .


script:
 - docker run nishadguru/docker-react npm run test -- --coverage

deploy:
 - docker build -f Dcokerfile .
 


